worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 9443 ssl;
        ssl_certificate /var/serving-cert/tls.crt;
        ssl_certificate_key /var/serving-cert/tls.key;

        root /opt/app-root/src;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
            add_header Cache-Control "no-cache";
        }

        location /plugin-manifest.json {
            add_header Cache-Control "no-cache";
        }
    }
}
